### ISSUE TITLE
Drawing is only allowed inside NOTIFICATION _DRAW, _draw() function or 'draw' signal

### ISSUE THREAD

**Issue by seffa1** [daveTheOldCoder/godot-radial-progress-indicator#2]
This error makes absolutely no sense. I have brought this code into my project and it works perfectly fine, except for this error message I get every frame.

Do you have any idea why? The code is calling draw's inside _draw and queue_redraw() is getting called.

This maybe could be related to https://github.com/godotengine/godot/issues/75376 ?

Let me know if you have any idea, thanks!

**Comment by daveTheOldCoder** [comment]
What is the Godot version in which the error was observed?

**Comment by seffa1** [comment]
Im in Godot 4.1.

I actually just figured out I needed the following change (remove _draw() and queue_redraw() in the setters).
Since queue_draw() is in the process function, _draw() should be getting called each frame, so calling it in the setters here is like calling _draw() twice in the same frame which will cause this error as well.



```
@export var max_value: float = 100.0:
	set(v):
		max_value = v
		#_draw()

@export var radius: float = 120.0:
	set(v):
		radius = v
		#queue_redraw()

@export var progress: float = 0.0:
	set(v):
		progress = v
		#queue_redraw()

@export var thickness: float = 20.0:
	set(v):
		thickness = v
		#queue_redraw()

@export var bg_color := Color(0.5, 0.5, 0.5, 1.0):
	set(v):
		bg_color = v
		#queue_redraw()

@export var bar_color := Color(0.2, 0.9, 0.2, 1.0):
	set(v):
		bar_color = v
		#queue_redraw()
```

**Comment by daveTheOldCoder** [comment]
Thanks for the additional information.

I don't know a lot about custom drawing in Godot. I created this Godot 4 plugin by making the minimal changes to a Godot 3 plugin.

I just tested your suggested change in Godot 4.3-beta1, and it worked correctly. I'll repeat the test in some other 4.x versions, and if it works correctly, I'll submit an update for the plugin.

**Comment by daveTheOldCoder** [comment]
Do you think it would be better to remove the _process() method, and leave the calls to _draw() and queue_redraw() in the setters? In my test, that works too. That has the advantage that the drawing calls occur only when needed, rather than every frame.

Could you test that and see if it removes the error?

**Comment by seffa1** [comment]
I would leave it in the _process() function since that guarentees it is only called once per frame.
In my implementation I am updating both the progress and the max progress each frame which which cause it to be called more than once.

I do agree there is some performance difference involved but I am not sure how much.

Anyways, here it is in action as a stamina/health meter. Thanks again !

https://github.com/daveTheOldCoder/godot-radial-progress-indicator/assets/94399429/900f8a91-9c81-4460-8a7b-88989b212c26

**Comment by daveTheOldCoder** [comment]
That makes sense.

I removed the setters, since their only purpose was to make the drawing calls.

I've committed the change here, and will shortly be submitting the new version to the Asset Library.

Thanks again for your help.

**Comment by daveTheOldCoder** [comment]
New version is 2.1.1:
https://github.com/daveTheOldCoder/godot-radial-progress-indicator/releases/tag/2.1.1
https://godotengine.org/asset-library/asset/2193
